server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-05-05T00:55:29.478666200+08:00[Asia/Shanghai]
            #- Cookie=username,caiwei
            #- Header=X-Request-Id, \d+              # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com
            #- Query=username, \d+
            #- RemoteAddr=172.24.139.1/24
            #- Method=POST,GET
            #- My=Gold


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
#            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
            - Path=/gateway/filter/**
          filters:
            - PrefixPath=/pay #真实地址需要将地址栏的地址添加前缀
            - MyFilter=atguigu
#            - AddRequestHeader=X-Request-atguigu1, Request_Header #添加参数到请求头
#            - RemoveRequestHeader=sec-fetch-site    #移除请求头中的某个参数
#            - SetRequestHeader=X-Request-atguigu1, CaiweiLoveSorako
#            - AddRequestParameter=Name, leiyujia
#            - RemoveRequestParameter=User,zhong
#            - AddResponseHeader=X-Request-Color,green
#            - RemoveResponseHeader=Content-Type
#            - SetResponseHeader=Date,2003-09-22
